### ISSUE TITLE
cannot uncheck telemetry gathering checkbox

### ISSUE THREAD

**Issue by maxandersen** [code-ready/cockpit-crc#17]
when instaling with podman the UI shows a checkbox stating one agrees for telemetry being sent to red hat, but one cannot uncheck it.

**Comment by cfergeau** [comment]
This is done on purpose, and is explained in the release notes:

https://github.com/code-ready/crc/releases/tag/dev-1.99.0
> The following is part of the development preview and will not be in the final release.
> Telemetry is enforced for this release to collect issues
